keywords = [
    # 'tv',
    # 'movie',
    # 'film',
    # 'likevideo',
    # 'livestream',
    # 'livevideo',
    'gamming',
    'tech',
    'project',
    'unboxing',
    'projector',
    'projectors',
    'technology',
    'ProjectorRetrofit',
    'projectorlights',
    'projectorheadlights',
    'projectorlamp',
    'projectorscreen',
    'projectorband',
    'projectorca',
    'projectordeath',
    'projectormapping',
    'ProjectorRetro',
    'projectormovie',
    'projectormurah',
    'projectorportrait',
    'projectorlift',
    'ProjectorScreens',
    'projectorsforrent',
    'projectormobil',
    'projectormetalband',
    'projectorlens',
    'projectorgram',
    'projectorganize',
    'projectorganic',
    'projectorevolver',
    'projectorder',
    'projectorart',
    'TechnologyRocks',
    'TechnologyTheseDays',
    'technologynews',
    'technologysolutions',
    'technologyfail',
    'technologyart',
    'technologytrends',
    'technologyr',
    'TechnologyIsAwesome',
    'technologysucks',
    'technologyhatesme',
    'technologyinnovation',
    'technologytoenjoy',
    'technologyaddict',
    'technologylover',
    'technologytuesday',
    'technologyrules',
    'technologywitch',
    'technologycompany',
    'technologytakeover',
    'technologybali',
    'TechnologyConsulting',
    'technologyeducation',
    'technologyfacts',
    'TechnologyforGood',
    'technologyfree',
    'technologyisamazing',
    'technologyiscool',
    'technologyjobs'
    'pet',
    'vacuum',
    'cleaner',
    'cleaningtips',
    'smarthome',
    'cleaninghacks',
    'technology',
    'cleantok',
    'home',
    'rugcleaning',
    'carpetwashing',
    'cleanhome',
    'wetanddryvacuum',
    'wetanddry',
    'autoclean',
    'autocleaning',
    'autocleaner',
    'dog',
    'food',
    'cat',
    'family',
    'puppy',
    'petlover',
    'pets',
    'petlife',
    'natureathome',
    'petvlog',
    'meetmypet',
    'mypet',
    'funnypets',
    'petvacuum',
    'vacuuming',
    'cleaners',
    'cleaningtip',
    'cleaninghack',
    'techtok',
    'futuretech',
    'dogs',
    'foodie',
    'desifood',
    'cats',
    'meow',
    'puppylove',
    'puppies',
    'animals',
    'foodblogger',
    'foodpics',
    'foodphotography',
    'foodlover',
    'foods',
    'foodblog',
    'foodart',
    'foodlovers',
    'fooddiary',
    'foodshare',
    'foodlove',
    'vacuumcleaner',
    'vacuumtherapy',
    'vacuumcupping',
    'vacuumcleanerportable',
    'vacuumcleaning',
    'vacuumed',
    'vacuumflask',
    'vacuumformer',
    'vacuummachine',
    'vacuumpacked',
    'vacuumbag',
    'vacuumbottle',
    'vacuumtelinga',
    'vacuumtungau',
    'technology',
    'technologynews',
    'technologysolutions',
    'technologyart',
    'technologytrends',
    'TechnologyIsAwesome',
    'technologyhatesme',
    'technologyinnovation',
    'technologytoenjoy',
    'technologyrules',
    'technologywitch',
    'technologyfacts',
    'technologyisamazing',
    'technologyiscool',
    'space',
    'mop',
    'sweeper',
    'towel',
    'swab',
    'duster',
    'Hoover',
    'household',
    'housekeeping',
    'homemaking',
    'chores',
    'explore',
    'boost',
    'trend',
    'trending',
    'cleantok',
    'vacuumsounds',
    'asmrsounds',
    'comedy',
    'featurethis',
    'featureme',
    'prank',
    '15svines',
    'trending',
    '1mincomedy',
    'blooper',
    '1minaudition'
]

proxy_url = {
    'ip': '127.0.0.1',
    # 'port': 1080
    'port': 7890

}

item_example = {"description": "PO Box 976 Greensburg PA 15601\nShe/Her\nVenmo: jjones0451\n⬇️ALL NEEDS BELOW⬇️",
                "email": "",
                "nickname": "Jordan",
                "tik_link": "https://www.tiktok.com/@jjones451",
                "social_link": "https://linktr.ee/jjones451",
                "fans": 1500000,
                "video_count": 3213,
                "create_time": 1544652250,
                "keyword": "petvacuum"}
